/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    EarthBrowser: typeof import('./src/components/EarthBrowser.vue')['default']
    EarthBrowserAppBar: typeof import('./src/components/EarthBrowserAppBar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ProjectScroll: typeof import('./src/components/ProjectScroll.vue')['default']
  }
}
